/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net_catering;

/**
 *
 * @author Admin
 */
public class create_use extends javax.swing.JPanel {

    /**
     * Creates new form create_use
     */
    public create_use() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        department_txt = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        email_txt = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        user_txt = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        phone_txt = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        id_txt = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        name_txt = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        re_pass_txt = new javax.swing.JPasswordField();
        pass_txt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(jLabel1, gridBagConstraints);

        department_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "User", "Manager", "Admin" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(department_txt, gridBagConstraints);

        email_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        jScrollPane4.setViewportView(email_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(jScrollPane4, gridBagConstraints);

        user_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jScrollPane5.setViewportView(user_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel3.add(jScrollPane5, gridBagConstraints);

        phone_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Telephone Number"));
        jScrollPane8.setViewportView(phone_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(jScrollPane8, gridBagConstraints);

        id_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("ID / Passport Number"));
        jScrollPane10.setViewportView(id_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(jScrollPane10, gridBagConstraints);

        name_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Full Name"));
        jScrollPane11.setViewportView(name_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(jScrollPane11, gridBagConstraints);

        jButton1.setText("Save Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton1, gridBagConstraints);

        re_pass_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(re_pass_txt, gridBagConstraints);

        pass_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(pass_txt, gridBagConstraints);

        jButton2.setText("Back To Main");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /* try {
            System.out.println( "try");
            Class.forName("org.postgresql.Driver");
            System.out.println("Org Postgres");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "admin", "12345678");
            System.out.println( "password");
            String user = user_txt.getText();
            String name = name_txt.getText();
            String password = pass_txt.getText();
            String confirmPassword = re_pass_txt.getText();
            String department = department_txt.getSelectedItem().toString();
            String email = email_txt.getText();
            String phone = phone_txt.getText();
            String id = id_txt.getText();

            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(null, "Passwords do not match");
                return; // Stop further execution
            }

            if (department.equals("-")) {
                JOptionPane.showMessageDialog(null, "Please select a valid department");
                return; // Stop further execution
            }

            String query = "INSERT INTO public.login_credentials( username, full_name, password, email, phone_no, id_no, department) VALUES (?, ?, ?, ?, ?, ?,?);";
            var pst = conn.prepareStatement(query);
            pst.setString(1, user);
            pst.setString(2, name);
            pst.setString(3, password);
            pst.setString(4, email);
            pst.setString(5, phone);
            pst.setString(6, id);
            pst.setString(7, department);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted successfully");

            // Clear the input fields
            user_txt.setText("");
            name_txt.setText("");
            pass_txt.setText("");
            re_pass_txt.setText("");
            department_txt.setSelectedIndex(0);
            email_txt.setText("");
            phone_txt.setText("");
            id_txt.setText("");

            //Homepa receptionist = new Homepage();
            // register_report.show();
        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main_Cafe clerkingModule = new Main_Cafe();
        //clerkingModule.setPersonaText(username); // Pass the username to Clerking module
        clerkingModule.setVisible(true); // Redirect to Clerking module
    //    dispose();
        //JOptionPane.showMessageDialog(this, "Login successful");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> department_txt;
    private javax.swing.JTextPane email_txt;
    private javax.swing.JTextPane id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane name_txt;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JTextPane phone_txt;
    private javax.swing.JPasswordField re_pass_txt;
    private javax.swing.JTextPane user_txt;
    // End of variables declaration//GEN-END:variables

    void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
